# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "JSDay Recife 2018"
email: "jsdaybr@gmail.com"
description: "O JSday é um evento imersivo focado em JavaScript e tudo o que essa linguagem tem a oferecer"
baseurl: ""
url: "http://jsday.com.br"
seasonUrl: "http://rec.jsday.com.br"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-62574701-1"
googleAnalyticsSiteUrl: "jsday.com.br"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "JSday Recife"
# organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "O JSday é um evento imersivo focado em JavaScript e tudo o que essa linguagem tem a oferecer"
organizerEmail: "jsdaybr@gmail.com"
# organizerLogo: "/img/seo/organizer-logo.png"
# organizerLink: "#"

# Head
metaKeywords: "event, javascript, js, angularjs, reactjs, accessibility, google maps, ionic, firebase, aplicativos híbridos, nodebots"
twitterAccount: "@jsdaybr"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4sponsorsUrl: "mailto:jsdaybr@gmail.com?subject=Patrocínio JSday Recife 2018"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/#about", text: "Sobre"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/#venue", text: "Local"}
 - {permalink: "/#partners", text: "Patrocinadores"}
 - {permalink: "/live/", text: "Live"}
#- {link: "https://goo.gl/forms/6kiJlTmUivVu9SVE3", text: "Call for Papers"}

#bottomNavigationLinks:
# - {link: "", text: ""}
rightNavigationButtons:
 - {link: "https://goo.gl/6grj38", text: "Inscreva-se.now(&#9829;)"}

# Hero Block
heroImage: ""
heroTitle: "<typeout>"
eventDate: "01 de Dezembro, 2018"
typeoutTextValues: '"JSday Recife", "ReactJS", "Web Performance", "Data Viz","Watson APIs via Node.js em Cloud functions", "Angular", "GitHub Essentials", "Experiências incríveis utilizando P5.js"'
typeoutFallback: "JSday Recife"
heroButtons:
- {link: "https://goo.gl/6grj38", text: "Inscreva-se.now(&#9829;)"}
#- {link: "https://goo.gl/forms/6kiJlTmUivVu9SVE3", text: "Sua palestra no JSDay"}
#- {link: "https://goo.gl/forms/YrQgSmaYEODYnj333", text: "Seja um voluntário"}

# About Block
aboutTitle: "Sobre o JSday Recife"
aboutBlock:
 - {title: "JavaScript", image: "javascript.jpg", text: "Como uma das linguagens mais populares e mais utilizadas atualmente, você pode encontrá-la no seu navegador, no seu smartphone e até em sua geladeira, seguindo o conceito de Internet das Coisas." }
 - {title: "Mercado", image: "office.jpg", text: "O mercado tem uma demanda gigantesca por profissionais que conhecem as nuances do JavaScript e estejam por dentro de suas novidades." }
 - {title: "Networking", image: "networking.jpg", text: "Uma das melhores formas para desenvolvimento profissional com certeza é conhecer a comunidade que você faz parte." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "Participantes", detail: "Empresas, profissionais e estudantes"}
 - {count: "+16", specialCharacter: "+", info: "Palestras", detail: "Duas trilhas com tópicos incríveis"}
 - {count: "8", specialCharacter: "+", info: "Horas", detail: "de puro código"}
 # - {count: "1", specialCharacter: "+", info: "Workshop e Codelab", detail: "Foco total em JavaScript"}

# Latest News Block
latestNewsTitle: "Novidades"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "JavaScript Experts"
rockstarSpeakersButtonText: "Conheça todos Palestrantes"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "Faculdade Imaculada Conceição do Recife (FICR)"
eventLocationLink: "https://www.ficr.edu.br/"
eventStreetAddress: "Avenida Caxangá 3841, 3841, Iputinga"
eventAddressLocality: "Recife"
eventAddressLocalityRegion: "PE"
eventPostalCode: "50670-902"
eventAddressCountry: "Brasil"
eventStartTime: "2018-12-16T08:00"
eventDoorTime: "08:00"
eventEndTime: "2018-12-16T18:00"
eventPlaceCoordinates: "-8.040965,-34.94011"
mapCenterCoordinates: "-8.040965,-34.94011"
mapMobileCenterCoordinates: "-8.0191395,-34.939734"

# Venue Block
venueBlockTitle: "Local"
venueBigImage: "ficr2018.jpg"
venueSmallImage1: "auditorio2018.jpg"
venueSmallImage2: "sala2018.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "FICR"
venueFeatures: ["Salas climatizadas e com tratamento acústico, labs de informática, cantina, elevador e um amplo estacionamento."]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Tweets.get()"
twitterHashTag: "jsdayrec"
twitterFeed: "#"

# Partners Block
organizersTitle: "Organização"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Ajude-nos a codificar. Patrocine!"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Inscreva-se.now()"
ticketsOffers:
 -
#  name: "teste"
#  price: ""
#  priceCurrency: ""
  buyButtonLink: "https://www.sympla.com.br/jsday-recife-2017__108032"
  buyButtonText: "{{Comprar}}"
#  validFrom: "YYYY-MM-DDThh:mm"
#  validThrough: "YYYY-MM-DDThh:mm"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=jsdaybr", icon: "twitter"}
 - {link: "https://www.facebook.com/jsdaybr/", icon: "facebook"}

footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://goo.gl/forms/YrQgSmaYEODYnj333", text: "Seja um voluntário"}
   - {link: "https://goo.gl/forms/6kiJlTmUivVu9SVE3", text: "Inscreva sua palestra"}
   - {link: "https://goo.gl/FkZGNL", text: "Nosso Midiakit"}
   - {link: "https://www.ficr.edu.br/", text: "Faculdade Imaculada Conceição do Recife - FICR"}
   #- {link: "https://www.udacity.com/", text: "Udacity"}
   #- {link: "https://www.maxmilhas.com.br/", text: "MaxMilhas"}
   #- {link: "http://www.stone.com.br/", text: "Stone"}
   #- {link: "http://artics.com.br/", text: "Artics"}
 -
  title: "Edições Anteriores"
  links:
   - {link: "http://rio.jsday.com.br", text: "Rio 2018"}
   - {link: "http://fsa.jsday.com.br", text: "Feira de Santana 2018"}
   - {link: "http://fsa.jsday.com.br/2017", text: "Feira de Santana 2017"}
   - {link: "http://rec.jsday.com.br/2017", text: "Recife 2017"}
   - {link: "http://rec.jsday.com.br/2016", text: "Recife 2016"}
   - {link: "http://rec.jsday.com.br/2015", text: "Recife 2015"}
   - {link: "http://cg.jsday.com.br", text: "Campina Grande 2016"}
   - {link: "http://mcz.jsday.com.br", text: "Maceió 2015"}
 -
  title: "Contato"
  links:
   - {link: "mailto:jsdaybr@gmail.com", text: "jsdaybr@gmail.com"}
   - {link: "mailto:felipealbuquerque81@gmail.com", text: "felipealbuquerque81@gmail.com"}
 -
  title: "FAQ"
  links:
   - {link: "https://goo.gl/FkZGNL", text: "Como patrocinar? Leia o nosso Midiakit!"}
   - {link: "http://pt-br.confcodeofconduct.com/", text: "Código de Conduta"}
#   - {link: "http://womentechmakers.com", text: "WTM (Women Techmakers)"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Call for Papers
cfpTitle: "Espalhe o amor pelo JavaScript"
cfpDescription: "Uma oportunidade excelente para você mostrar do que o JavaScript é capaz. Se você já está por dentro das novidades de ES2015 e ES2016, sabe utilizar componentes React ou Angular como ninguém, programa usando JavaScript funcional e reativo ou ainda quer explicar do que se trata esse tal de Babel, participe do JSDay e ajude a comunidade crescer."
cfpLink: "https://www.sympla.com.br/jsday-recife-2017__108032"
cfpLinkText: "Inscreva-se <3"

# O que esperar do JSDay Recife 2018?
oqjsday2016Title: "O que esperar do JSDay Recife 2018?"
oqjsday2016Description: "Palestras com alguns dos melhores especialistas da área, trocas de ideias, atividades práticas, sorteios, networking e várias outras surpresas - é isso que os participantes do JSDay encontrarão."
oqjsday2016Link: "#"
oqjsday2016LinkText: "Leia mais"

#WTM JavaScript Codelab
wtmCodelabTitle: "WTM JavaScript Codelab"
trainingImage: "womentechmakers.jpg"
trainingTitle: "Instrutora"
wtmJavaScriptCodelabRows:
 - {title: "Codelab Gratuito para Mulheres", image: "1.png", details: "O WTM JavaScript Codelab tem como objetivo ensinar o básico dessa poderosa linguagem para meninas que se interessam em se aventurar no Desenvolvimento Web. As mesmas meninas que participarem desse Codelab poderão assistir as palestras da tarde do JSday e ver o quão versátil é o que elas aprenderam pela manhã.﻿"}
 - {title: "Por que JavaScript?", image: "2.png", details: "Uma das linguagens mais populares e mais utilizadas atualmente, você pode encontrá-la no seu navegador, no seu smartphone e até em sua geladeira, seguindo o conceito de Internet das Coisas.<br><br>Hoje o JavaScript está entrando num processo de evolução, inovação e padronização, com novos desenvolvimentos, como Node.js, permitindo usar o JavaScript no servidor, além de APIs HTML5 para obter dados sobre a localização de dispositivos e características geográficas e muito mais."}

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false


# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
